In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\admin\Downloads\archive\UCI_Credit_Card.csv",delimiter=',',error_bad_lines= False)
print("The first 5 rows of the dataframe") 
df.head(5)

C:\Users\admin\AppData\Local\Temp/ipykernel_20180/2554273148.py:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(r"C:\Users\admin\Downloads\archive\UCI_Credit_Card.csv",delimiter=',',error_bad_lines= False)

The first 5 rows of the dataframe

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [6]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [7]:
df.dtypes

ID                              int64
LIMIT_BAL                     float64
SEX                             int64
EDUCATION                       int64
MARRIAGE                        int64
AGE                             int64
PAY_0                           int64
PAY_2                           int64
PAY_3                           int64
PAY_4                           int64
PAY_5                           int64
PAY_6                           int64
BILL_AMT1                     float64
BILL_AMT2                     float64
BILL_AMT3                     float64
BILL_AMT4                     float64
BILL_AMT5                     float64
BILL_AMT6                     float64
PAY_AMT1                      float64
PAY_AMT2                      float64
PAY_AMT3                      float64
PAY_AMT4                      float64
PAY_AMT5                      float64
PAY_AMT6                      float64
default.payment.next.month      int64
dtype: object

In [8]:
df.corr()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
ID,1.000000,0.026179,0.018497,0.039177,-0.029079,0.018678,-0.030575,-0.011215,-0.018494,-0.002735,...,0.040351,0.016705,0.016730,0.009742,0.008406,0.039151,0.007793,0.000652,0.003000,-0.013952
LIMIT_BAL,0.026179,1.000000,0.024755,-0.219161,-0.108139,0.144713,-0.271214,-0.296382,-0.286123,-0.267460,...,0.293988,0.295562,0.290389,0.195236,0.178408,0.210167,0.203242,0.217202,0.219595,-0.153520
SEX,0.018497,0.024755,1.000000,0.014232,-0.031389,-0.090874,-0.057643,-0.070771,-0.066096,-0.060173,...,-0.021880,-0.017005,-0.016733,-0.000242,-0.001391,-0.008597,-0.002229,-0.001667,-0.002766,-0.039961
EDUCATION,0.039177,-0.219161,0.014232,1.000000,-0.143464,0.175061,0.105364,0.121566,0.114025,0.108793,...,-0.000451,-0.007567,-0.009099,-0.037456,-0.030038,-0.039943,-0.038218,-0.040358,-0.037200,0.028006
MARRIAGE,-0.029079,-0.108139,-0.031389,-0.143464,1.000000,-0.414170,0.019917,0.024199,0.032688,0.033122,...,-0.023344,-0.025393,-0.021207,-0.005979,-0.008093,-0.003541,-0.012659,-0.001205,-0.006641,-0.024339
AGE,0.018678,0.144713,-0.090874,0.175061,-0.414170,1.000000,-0.039447,-0.050148,-0.053048,-0.049722,...,0.051353,0.049345,0.047613,0.026147,0.021785,0.029247,0.021379,0.022850,0.019478,0.013890
PAY_0,-0.030575,-0.271214,-0.057643,0.105364,0.019917,-0.039447,1.000000,0.672164,0.574245,0.538841,...,0.179125,0.180635,0.176980,-0.079269,-0.070101,-0.070561,-0.064005,-0.058190,-0.058673,0.324794
PAY_2,-0.011215,-0.296382,-0.070771,0.121566,0.024199,-0.050148,0.672164,1.000000,0.766552,0.662067,...,0.222237,0.221348,0.219403,-0.080701,-0.058990,-0.055901,-0.046858,-0.037093,-0.036500,0.263551
PAY_3,-0.018494,-0.286123,-0.066096,0.114025,0.032688,-0.053048,0.574245,0.766552,1.000000,0.777359,...,0.227202,0.225145,0.222327,0.001295,-0.066793,-0.053311,-0.046067,-0.035863,-0.035861,0.235253
PAY_4,-0.002735,-0.267460,-0.060173,0.108793,0.033122,-0.049722,0.538841,0.662067,0.777359,1.000000,...,0.245917,0.242902,0.239154,-0.009362,-0.001944,-0.069235,-0.043461,-0.033590,-0.026565,0.216614
PAY_5,-0.022199,-0.249411,-0.055064,0.097520,0.035629,-0.053826,0.509426,0.622780,0.686775,0.819835,...,0.271915,0.269783,0.262509,-0.006089,-0.003191,0.009062,-0.058299,-0.033337,-0.023027,0.204149
PAY_6,-0.020270,-0.235195,-0.044008,0.082316,0.034345,-0.048773,0.474553,0.575501,0.632684,0.716449,...,0.266356,0.290894,0.285091,-0.001496,-0.005223,0.005834,0.019018,-0.046434,-0.025299,0.186866
BILL_AMT1,0.019389,0.285430,-0.033642,0.023581,-0.023472,0.056239,0.187068,0.234887,0.208473,0.202812,...,0.860272,0.829779,0.802650,0.140277,0.099355,0.156887,0.158303,0.167026,0.179341,-0.019644
BILL_AMT2,0.017982,0.278314,-0.031183,0.018749,-0.021602,0.054283,0.189859,0.235257,0.237295,0.225816,...,0.892482,0.859778,0.831594,0.280365,0.100851,0.150718,0.147398,0.157957,0.174256,-0.014193
BILL_AMT3,0.024354,0.283236,-0.024563,0.013002,-0.024909,0.053710,0.179785,0.224146,0.227494,0.244983,...,0.923969,0.883910,0.853320,0.244335,0.316936,0.130011,0.143405,0.179712,0.182326,-0.014076
BILL_AMT4,0.040351,0.293988,-0.021880,-0.000451,-0.023344,0.051353,0.179125,0.222237,0.227202,0.245917,...,1.000000,0.940134,0.900941,0.233012,0.207564,0.300023,0.130191,0.160433,0.177637,-0.010156
BILL_AMT5,0.016705,0.295562,-0.017005,-0.007567,-0.025393,0.049345,0.180635,0.221348,0.225145,0.242902,...,0.940134,1.000000,0.946197,0.217031,0.181246,0.252305,0.293118,0.141574,0.164184,-0.006760
BILL_AMT6,0.016730,0.290389,-0.016733,-0.009099,-0.021207,0.047613,0.176980,0.219403,0.222327,0.239154,...,0.900941,0.946197,1.000000,0.199965,0.172663,0.233770,0.250237,0.307729,0.115494,-0.005372
PAY_AMT1,0.009742,0.195236,-0.000242,-0.037456,-0.005979,0.026147,-0.079269,-0.080701,0.001295,-0.009362,...,0.233012,0.217031,0.199965,1.000000,0.285576,0.252191,0.199558,0.148459,0.185735,-0.072929
PAY_AMT2,0.008406,0.178408,-0.001391,-0.030038,-0.008093,0.021785,-0.070101,-0.058990,-0.066793,-0.001944,...,0.207564,0.181246,0.172663,0.285576,1.000000,0.244770,0.180107,0.180908,0.157634,-0.058579
PAY_AMT3,0.039151,0.210167,-0.008597,-0.039943,-0.003541,0.029247,-0.070561,-0.055901,-0.053311,-0.069235,...,0.300023,0.252305,0.233770,0.252191,0.244770,1.000000,0.216325,0.159214,0.162740,-0.056250
PAY_AMT4,0.007793,0.203242,-0.002229,-0.038218,-0.012659,0.021379,-0.064005,-0.046858,-0.046067,-0.043461,...,0.130191,0.293118,0.250237,0.199558,0.180107,0.216325,1.000000,0.151830,0.157834,-0.056827
PAY_AMT5,0.000652,0.217202,-0.001667,-0.040358,-0.001205,0.022850,-0.058190,-0.037093,-0.035863,-0.033590,...,0.160433,0.141574,0.307729,0.148459,0.180908,0.159214,0.151830,1.000000,0.154896,-0.055124
PAY_AMT6,0.003000,0.219595,-0.002766,-0.037200,-0.006641,0.019478,-0.058673,-0.036500,-0.035861,-0.026565,...,0.177637,0.164184,0.115494,0.185735,0.157634,0.162740,0.157834,0.154896,1.000000,-0.053183
default.payment.next.month,-0.013952,-0.153520,-0.039961,0.028006,-0.024339,0.013890,0.324794,0.263551,0.235253,0.216614,...,-0.010156,-0.006760,-0.005372,-0.072929,-0.058579,-0.056250,-0.056827,-0.055124,-0.053183,1.000000

In [9]:
df.corr()["default.payment.next.month"]

ID                           -0.013952
LIMIT_BAL                    -0.153520
SEX                          -0.039961
EDUCATION                     0.028006
MARRIAGE                     -0.024339
AGE                           0.013890
PAY_0                         0.324794
PAY_2                         0.263551
PAY_3                         0.235253
PAY_4                         0.216614
PAY_5                         0.204149
PAY_6                         0.186866
BILL_AMT1                    -0.019644
BILL_AMT2                    -0.014193
BILL_AMT3                    -0.014076
BILL_AMT4                    -0.010156
BILL_AMT5                    -0.006760
BILL_AMT6                    -0.005372
PAY_AMT1                     -0.072929
PAY_AMT2                     -0.058579
PAY_AMT3                     -0.056250
PAY_AMT4                     -0.056827
PAY_AMT5                     -0.055124
PAY_AMT6                     -0.053183
default.payment.next.month    1.000000
Name: default.payment.next.month, dtype: float64

In [10]:
lst=["LIMIT_BAL", "SEX","EDUCATION", "MARRIAGE", "AGE", "PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6", "BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6", "PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"]
lst2=[]
from scipy.stats import pearsonr
for i in lst:
    corr,_ = pearsonr(df["default.payment.next.month"],df[i])
    print(i,'Pearsons correlation: %.3f' % corr)
    if corr<-0.5 or corr>0.5:
        lst2.append(i)
print(lst2)

LIMIT_BAL Pearsons correlation: -0.154
SEX Pearsons correlation: -0.040
EDUCATION Pearsons correlation: 0.028
MARRIAGE Pearsons correlation: -0.024
AGE Pearsons correlation: 0.014
PAY_0 Pearsons correlation: 0.325
PAY_2 Pearsons correlation: 0.264
PAY_3 Pearsons correlation: 0.235
PAY_4 Pearsons correlation: 0.217
PAY_5 Pearsons correlation: 0.204
PAY_6 Pearsons correlation: 0.187
BILL_AMT1 Pearsons correlation: -0.020
BILL_AMT2 Pearsons correlation: -0.014
BILL_AMT3 Pearsons correlation: -0.014
BILL_AMT4 Pearsons correlation: -0.010
BILL_AMT5 Pearsons correlation: -0.007
BILL_AMT6 Pearsons correlation: -0.005
PAY_AMT1 Pearsons correlation: -0.073
PAY_AMT2 Pearsons correlation: -0.059
PAY_AMT3 Pearsons correlation: -0.056
PAY_AMT4 Pearsons correlation: -0.057
PAY_AMT5 Pearsons correlation: -0.055
PAY_AMT6 Pearsons correlation: -0.053
[]

In [50]:
from sklearn.model_selection import train_test_split

#divide x_data and y_data
y_data = df['default.payment.next.month']
x_data=df.drop(['default.payment.next.month','ID'],axis=1)

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=1)
#random_state=1 gives you different results everytime

print("Number of test samples :", x_test.shape[0])
print("Number of training samples:",x_train.shape[0])

Number of test samples : 9000
Number of training samples: 21000

In [51]:
############## LOGISTIC REGRESSION

from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0,class_weight="balanced").fit(x_train,y_train)
LR

C:\Users\admin\anaconda3\envs\dmw5\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', random_state=0)

In [52]:
yhat1 = LR.predict(x_test)
yhat1

array([0, 1, 0, ..., 0, 1, 1], dtype=int64)

In [53]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat1)

0.26796772377556766

In [54]:
from sklearn.metrics import log_loss
log_loss(y_test, yhat1)

14.970936508487965

In [55]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix,precision_score, recall_score, f1_score, accuracy_score
confusion_matrix(y_test, yhat1, labels=[1,0])

array([[1428,  572],
       [3329, 3671]], dtype=int64)

In [56]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, yhat1, average='macro')

(0.5826894595612128, 0.6192142857142857, 0.5378506674391226, None)

In [57]:
print('Precision: %.3f' % precision_score(y_test, yhat1))
print('Recall: %.3f' % recall_score(y_test, yhat1))
print('Accuracy: %.3f' % accuracy_score(y_test, yhat1))
print('F1 Score: %.3f' % f1_score(y_test, yhat1))

Precision: 0.300
Recall: 0.714
Accuracy: 0.567
F1 Score: 0.423

In [66]:
####################### KNN

from sklearn.neighbors import KNeighborsClassifier
k = 3
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(x_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=3)

In [67]:
knnyhat = neigh.predict(x_test)
knnyhat[0:10]

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [68]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, knnyhat)

0.15682788051209104

In [69]:
from sklearn.metrics import log_loss
log_loss(y_test, knnyhat)

9.099120900605174

In [70]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, knnyhat, labels=[1,0])

array([[ 441, 1559],
       [ 812, 6188]], dtype=int64)

In [71]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, knnyhat, average='macro')

(0.5753580589494727, 0.55225, 0.5551779370591478, None)

In [72]:
print('Precision: %.3f' % precision_score(y_test, knnyhat))
print('Recall: %.3f' % recall_score(y_test, knnyhat))
print('Accuracy: %.3f' % accuracy_score(y_test, knnyhat))
print('F1 Score: %.3f' % f1_score(y_test, knnyhat))

Precision: 0.352
Recall: 0.221
Accuracy: 0.737
F1 Score: 0.271

In [84]:
############ DECISION TREE

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
decision_tree = tree.DecisionTreeClassifier(criterion="entropy", max_depth = 5)
decision_tree = decision_tree.fit(x_train, y_train)

In [85]:
ypred = decision_tree.predict(x_test)
score = accuracy_score(y_test, ypred)
print(score)

0.8197777777777778

In [86]:
score1 = decision_tree.score(x_test, y_test)
print(score1)

0.8197777777777778

In [ ]:
# Models according to their performance:
# 1. Decision Tree
# 2. Logistic Regression
# 3. KNN